name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
       - run: |
          # Exists since using github.action_path + path to main script doesn't work because bash
          # interprets the backslashes in github.action_path (which are used when the runner OS
          # is Windows) destroying the path to the target file.
          #
          # Also semicolons are necessary because I can't get the newlines to work
          entrypoint="import sys;
          import subprocess;
          from pathlib import Path;
          MAIN_SCRIPT = Path(r'${GITHUB_ACTION_PATH}') / 'action' / 'main.py';
          proc = subprocess.run([sys.executable, str(MAIN_SCRIPT)]);
          sys.exit(proc.returncode)
          "
          if [ "$RUNNER_OS" == "Windows" ]; then
            echo $entrypoint | python
          else
            echo $entrypoint | python3
          fi
          env:
            # TODO: Remove once https://github.com/actions/runner/issues/665 is fixed.
            INPUT_OPTIONS: ${{ inputs.options }}
            INPUT_SRC: ${{ inputs.src }}
            INPUT_BLACK_ARGS: ${{ inputs.black_args }}
            INPUT_VERSION: ${{ inputs.version }}
            pythonioencoding: utf-8
          shell: bash
